first_name = input("What is your first name? ")
last_name = input("What is your last name? ")
email_address = input("What is your email address? ")
phone_number = input("What is your phone number? ")
job = input("What is your job title? ")
id_number = input("What is your id number? ")
hair = input("What is your hair color? ")
month = input("Starting month? ")
eyes = input("What is your eyes color? ")
training = input("Complete additional training? ")

print("\nThe ID Card is: ")
print("_______________________________")
print(f"{last_name.upper()}, {first_name.capitalize()}")
print(job.title())
print(f"ID: {id_number}")
print()
print(email_address.lower())
print(phone_number)
print()
print(f"Hair: {hair.capitalize():15} Eyes: {eyes.capitalize()}")
print(f"Month: {month.capitalize():14} Training: {training.capitalize()}")
print("_______________________________")