print("\nPlease enter the following: ")
print()
adjective = input("adjective: ")
superlative = input("superlative: ")
noun = input("noun: ")
adjective_01  = input("adjective: ")
adjective_02 = input("adjective: ")
noun_01 = input("noun: ")
noun_02 = input("noun: ")
noun_03 = input("noun: ")
verb = input("verb: ")
verb_01 = input("verb: ")

print("\nYour story is: ")
print()
print("My cubicle is " + adjective + " ." + "It is the " + superlative + " cubicle in the office. I ")
print("have a " + noun + " on my desk next to a(n) " + adjective_01 + " . In my drawer, ")
print("I also have a(n) " + adjective_02 + noun_01 + " . One time a coworker tried to " + verb)
print("a " + noun_02 + " on my desk. I said to him, 'Hey!' how would you like it if I " + verb_01)
print("your " + noun_03 + " I will do it if you don't leave.")
print()