child = float(input("What is the price os a child's meal ? "))
adult = float(input("What is the price os a adult's meal ? "))
children_num = int(input("How many children are there ? " ))
adult_num = int(input("How many adults are there ? " ))
drinks = int(input("How many drinks ? "))
appetizers = int(input("Would you like an appetizers? How many would you like? "))

tax = float(input("What is the sales tax rate ? " ))
child_price = float(children_num * child)
adult_price = float(adult_num * adult)
drinks_price = float(2.50 * drinks)
appetizers_price = float(1.8 * appetizers)
subtotal = float(child_price + adult_price +drinks_price + appetizers_price )
sales_tax = (float(subtotal * float(tax)))/100
total = float(subtotal + sales_tax)
print()
print(f"Subtotal: ${subtotal}")
print(f"Sales Tax: ${sales_tax} ")
print(f"Total: ${total} ")
print()
amount = int(input("What is the payment amount ? " ))
change = float(amount - total)
print(f"Change: ${change:.2f} ")